# Generated by Django 5.2.6 on 2025-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry-level'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('top', 'Top-level')], default='mid', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('office', 'Office'), ('hybrid', 'Hybrid')], default='office', max_length=20),
        ),
    ]
